<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
if ( ! function_exists('city'))
{
	function city(){
		$city = array(
			'101' => 'Hà Nội',
			'103' => 'Hải Phòng',
			'104' => 'Vĩnh Phúc',
			'105' => 'Hà Tây',
			'106' => 'Bắc Ninh',
			'107' => 'Hải Dương',
			'109' => 'Hưng Yên',
			'111' => 'Hà Nam',
			'113' => 'Nam Định',
			'115' => 'Thái Bình',
			'117' => 'Ninh Bình',
			'201' => 'Hà Giang',
			'203' => 'Cao Bằng',
			'205' => 'Lào Cai',
			'207' => 'Bắc Kạn',
			'209' => 'Lạng Sơn',
			'211' => 'Tuyên Quang',
			'213' => 'Yên Bái',
			'215' => 'Thái Nguyên',
			'217' => 'Phú Thọ',
			'221' => 'Bắc Giang',
			'225' => 'Quảng Ninh',
			'301' => 'Lai Châu',
			'303' => 'Sơn La',
			'305' => 'Hòa Bình',
			'401' => 'Thanh Hóa',
			'403' => 'Nghệ An',
			'405' => 'Hà Tĩnh',
			'407' => 'Quảng Bình',
			'409' => 'Quảng Trị',
			'411' => 'Thừa Thiên - Huế',
			'501' => 'Thành phố Đà Nẵng',
			'503' => 'Quảng Nam',
			'505' => 'Quảng Ngãi',
			'507' => 'Bình Định',
			'509' => 'Phú Yên',
			'511' => 'Khánh Hòa',
			'601' => 'Kon Tum',
			'603' => 'Gia Lai',
			'605' => 'Đắk Lắk',
			'701' => 'Thành phố Hồ Chí Minh',
			'703' => 'Lâm Đồng',
			'705' => 'Ninh Thuận',
			'707' => 'Bình Phước',
			'709' => 'Tây Ninh',
			'711' => 'Bình Dương',
			'713' => 'Đồng Nai',
			'715' => 'Bình Thuận',
			'717' => 'BR-VT',
			'801' => 'Long An',
			'803' => 'Đồng Tháp',
			'805' => 'An Giang',
			'807' => 'Tiền Giang',
			'809' => 'Vĩnh Long',
			'811' => 'Bến Tre',
			'813' => 'Kiên Giang',
			'815' => 'Cần Thơ',
			'817' => 'Trà Vinh',
			'819' => 'Sóc Trăng',
			'821' => 'Bạc Liêu',
			'823' => 'Cà Mau'
		);
		
		return $city;
	}
}

if ( ! function_exists('districts'))
{
	function districts(){
		$districts = array(
							'101' => array('1' => 'Không xác định', 
											'2' => 'Quận Ba Đình', 
											'3' => 'Quận Long Biên', 
											'4' => 'Quận Tây Hồ', 
											'5' => 'Quận Hoàng Mai', 
											'6' => 'Quận Hoàn Kiếm', 
											'7' => 'Quận Hai Bà Trưng', 
											'8' => 'Quận Đống Đa', 
											'9' => 'Quận Thanh Xuân', 
											'10' => 'Quận Cầu Giấy', 
											'11' => 'Huyện Sóc Sơn', 
											'12' => 'Huyện Đông Anh', 
											'13' => 'Huyện Gia Lâm', 
											'14' => 'Huyện Từ Liêm', 
											'15' => 'Huyện Thanh Trì'
							), 
							'103' => array('16' => 'Không xác định', 
											'17' => 'Quận Hồng Bàng', 
											'18' => 'Quận Ngô Quyền', 
											'19' => 'Quận Lê Chân', 
											'20' => 'Quận Kiến An', 
											'21' => 'Thị xã Đồ Sơn', 
											'22' => 'Huyện Thuỷ Nguyên', 
											'23' => 'Huyện An Hải', 
											'24' => 'Huyện An Lão', 
											'25' => 'Huyện Kiến Thuỵ', 
											'26' => 'Huyện Tiên Lãng', 
											'27' => 'Huyện Vĩnh Bảo', 
											'28' => 'Huyện Cát Hải', 
											'29' => 'Huyện Bạch Long Vĩ'
							), 
							'104' => array('30' => 'Không xác định', 
											'31' => 'Thị xã Vĩnh Yên', 
											'32' => 'Huyện Lập Thạch', 
											'33' => 'Huyện Tam Dương', 
											'34' => 'Huyện Vĩnh Tường', 
											'35' => 'Huyện Yên Lạc', 
											'36' => 'Huyện Mê Linh', 
											'37' => 'Huyện Bình Xuyên'
							), 
							'105' => array('38' => 'Không xác định', 
											'39' => 'Thị xã Hà Đông', 
											'40' => 'Thị xã Sơn Tây', 
											'41' => 'Huyện Ba Vì', 
											'42' => 'Huyện Phúc Thọ', 
											'43' => 'Huyện Đan Phượng', 
											'44' => 'Huyện Thạch Thất', 
											'45' => 'Huyện Hoài Đức', 
											'46' => 'Huyện Quốc Oai', 
											'47' => 'Huyện Chương Mỹ', 
											'48' => 'Huyện Thanh Oai', 
											'49' => 'Huyện Thường Tín', 
											'50' => 'Huyện Mỹ Đức', 
											'51' => 'Huyện ứng Hòa', 
											'52' => 'Huyện Phú Xuyên'
							), 
							'106' => array('53' => 'Không xác định', 
											'54' => 'Thị xã Bắc Ninh', 
											'55' => 'Huyện Yên Phong', 
											'56' => 'Huyện Quế Võ', 
											'57' => 'Huyện Tiên Du', 
											'58' => 'Huyện Từ Sơn', 
											'59' => 'Huyện Thuận Thành', 
											'60' => 'Huyện Lương Tài', 
											'61' => 'Huyện Gia Bình'
							), 
							'107' => array('62' => 'Không xác định', 
											'63' => 'Thành phố Hải Dương', 
											'64' => 'Huyện Chí Linh', 
											'65' => 'Huyện Nam Sách', 
											'66' => 'Huyện Thanh Hà', 
											'67' => 'Huyện Kinh Môn', 
											'68' => 'Huyện Kim Thành', 
											'69' => 'Huyện Gia Lộc', 
											'70' => 'Huyện Tứ Kỳ', 
											'71' => 'Huyện Cẩm Giàng', 
											'72' => 'Huyện Bình Giang', 
											'73' => 'Huyện Thanh Miện', 
											'74' => 'Huyện Ninh Giang' 
							), 
							'109' => array('75' => 'Không xác định', 
											'76' => 'Thị xã Hưng Yên', 
											'77' => 'Huyện Văn Lâm', 
											'78' => 'Huyện Mỹ Văn', 
											'79' => 'Huyện Yên Mỹ', 
											'80' => 'Huyện Châu Giang', 
											'81' => 'Huyện Khoái Châu', 
											'82' => 'Huyện Ân Thi', 
											'83' => 'Huyện Kim Động', 
											'84' => 'Huyện Phù Cừ', 
											'85' => 'Huyện Tiên Lữ'
							), 
							'111' => array('86' => 'Không xác định', 
											'87' => 'Thị xã Phủ Lý', 
											'88' => 'Huyện Duy Tiên', 
											'89' => 'Huyện Kim Bảng', 
											'90' => 'Huyện Lý Nhân', 
											'91' => 'Huyện Thanh Liêm', 
											'92' => 'Huyện Bình Lục' 
							), 
							'113' => array('93' => 'Không xác định', 
											'94' => 'Thành phố Nam Định', 
											'95' => 'Huyện Vụ Bản', 
											'96' => 'Huyện Mỹ Lộc', 
											'97' => 'Huyện ý Yên', 
											'98' => 'Huyện Nam Trực', 
											'99' => 'Huyện Trực Ninh', 
											'100' => 'Huyện Xuân Trường', 
											'101' => 'Huyện Giao Thủy', 
											'102' => 'Huyện Nghĩa Hưng', 
											'103' => 'Huyện Hải Hậu'
							), 
							'115' => array('104' => 'Không xác định', 
											'105' => 'Thị xã Thái Bình', 
											'106' => 'Huyện Quỳnh Phụ', 
											'107' => 'Huyện Hưng Hà', 
											'108' => 'Huyện Thái Thụy', 
											'109' => 'Huyện Đông Hưng', 
											'110' => 'Huyện Vũ Thư', 
											'111' => 'Huyện Kiến Xương', 
											'112' => 'Huyện Tiền Hải', 
							), 
							'117' => array('113' => 'Không xác định', 
											'114' => 'Thị xã Ninh Bình', 
											'115' => 'Thị xã Tam Điệp', 
											'116' => 'Huyện Nho Quan', 
											'117' => 'Huyện Gia Viễn', 
											'118' => 'Huyện Hoa Lư', 
											'119' => 'Huyện Yên Mô', 
											'120' => 'Huyện Yên Khánh', 
											'121' => 'Huyện Kim Sơn', 
							), 
							'201' => array('122' => 'Không xác định', 
											'123' => 'Thị xã Hà Giang', 
											'124' => 'Huyện Đồng Văn', 
											'125' => 'Huyện Mèo Vạc', 
											'126' => 'Huyện Yên Minh', 
											'127' => 'Huyện Quản Bạ', 
											'128' => 'Huyện Bắc Mê', 
											'129' => 'Huyện Hoàng Su Phì', 
											'130' => 'Huyện Vị Xuyên', 
											'131' => 'Huyện Xín Mần', 
											'132' => 'Huyện Bắc Quang', 
							), 
							'203' => array('133' => 'Không xác định', 
											'134' => 'Thị xã Cao Bằng', 
											'135' => 'Huyện Bảo Lạc', 
											'136' => 'Huyện Hà Quảng', 
											'137' => 'Huyện Thông Nông', 
											'138' => 'Huyện Trà Lĩnh', 
											'139' => 'Huyện Trùng Khánh', 
											'140' => 'Huyện Nguyên Bình', 
											'141' => 'Huyện Hoà An', 
											'142' => 'Huyện Quảng Hoà', 
											'143' => 'Huyện Hạ Lang', 
											'144' => 'Huyện Thạch An', 
							), 
							'205' => array('145' => 'Không xác định', 
											'146' => 'Thị xã Lào Cai', 
											'147' => 'Thị xã Cam Đường', 
											'148' => 'Huyện Mường Khương', 
											'149' => 'Huyện Bát Xát', 
											'150' => 'Huyện Bắc Hà', 
											'151' => 'Huyện Bảo Thắng', 
											'152' => 'Huyện Sa Pa', 
											'153' => 'Huyện Bảo Yên', 
											'154' => 'Huyện Than Uyên', 
											'155' => 'Huyện Văn Bàn', 
							), 
							'207' => array('156' => 'Không xác định', 
											'157' => 'Thị xã Bắc Kạn', 
											'158' => 'Huyện Ba Bể', 
											'159' => 'Huyện Ngân Sơn', 
											'160' => 'Huyện Chợ Đồn', 
											'161' => 'Huyện Na Rì', 
											'162' => 'Huyện Bạch Thông', 
											'163' => 'Huyện Chợ Mới', 
							), 
							'209' => array('164' => 'Không xác định', 
											'165' => 'Thị xã Lạng Sơn', 
											'166' => 'Huyện Tràng Định', 
											'167' => 'Huyện Văn Lãng', 
											'168' => 'Huyện Bình Gia', 
											'169' => 'Huyện Bắc Sơn', 
											'170' => 'Huyện Văn Quan', 
											'171' => 'Huyện Cao Lộc', 
											'172' => 'Huyện Lộc Bình', 
											'173' => 'Huyện Chi Lăng', 
											'174' => 'Huyện Đình Lập', 
											'175' => 'Huyện Hữu Lũng', 
							), 
							'211' => array('176' => 'Không xác định', 
											'177' => 'Thị xã Tuyên Quang', 
											'178' => 'Huyện Nà Hang', 
											'179' => 'Huyện Chiêm Hóa', 
											'180' => 'Huyện Hàm Yên', 
											'181' => 'Huyện Yên Sơn', 
											'182' => 'Huyện Sơn Dương', 
							), 
							'213' => array('183' => 'Không xác định', 
											'184' => 'Thị xã Yên Bái', 
											'185' => 'Thị xã Nghĩa Lộ', 
											'186' => 'Huyện Lục Yên', 
											'187' => 'Huyện Văn Yên', 
											'188' => 'Huyện Mù Căng Chải', 
											'189' => 'Huyện Trấn Yên', 
											'190' => 'Huyện Yên Bình', 
											'191' => 'Huyện Văn Chấn', 
											'192' => 'Huyện Trạm Tấu', 
							), 
							'215' => array('193' => 'Không xác định', 
											'194' => 'Thành phố Thái Nguyên', 
											'195' => 'Thị xã Sông Công', 
											'196' => 'Huyện Định Hóa', 
											'197' => 'Huyện Võ Nhai', 
											'198' => 'Huyện Phú Lương', 
											'199' => 'Huyện Đồng Hỷ', 
											'200' => 'Huyện Đại Từ', 
											'201' => 'Huyện Phú Bình', 
											'202' => 'Huyện Phổ Yên', 
							), 
							'217' => array('203' => 'Không xác định', 
											'204' => 'Thành phố Việt Trì', 
											'205' => 'Thị xã Phú Thọ', 
											'206' => 'Huyện Đoan Hùng', 
											'207' => 'Huyện Hạ Hoà', 
											'208' => 'Huyện Thanh Ba', 
											'209' => 'Huyện Phong Châu', 
											'210' => 'Huyện Lâm Thao', 
											'211' => 'Huyện Sông Thao', 
											'212' => 'Huyện Yên Lập', 
											'213' => 'Huyện Tam Thanh', 
											'214' => 'Huyện Thanh Thuỷ', 
											'215' => 'Huyện Thanh Sơn', 
							), 
							'221' => array('216' => 'Không xác định', 
											'217' => 'Thị xã Bắc Giang', 
											'218' => 'Huyện Yên Thế', 
											'219' => 'Huyện Tân Yên', 
											'220' => 'Huyện Lục Ngạn', 
											'221' => 'Huyện Hiệp Hòa', 
											'222' => 'Huyện Lạng Giang', 
											'223' => 'Huyện Sơn Động', 
											'224' => 'Huyện Lục Nam', 
											'225' => 'Huyện Việt Yên', 
											'226' => 'Huyện Yên Dũng', 
							), 
							'225' => array('227' => 'Không xác định', 
											'228' => 'Thành phố Hạ Long', 
											'229' => 'Thị xã Cẩm Phả', 
											'230' => 'Thị xã Uông Bí', 
											'231' => 'Huyện Bình Liêu', 
											'232' => 'Thị Xã Móng Cái', 
											'233' => 'Huyện Quảng Hà', 
											'234' => 'Huyện Tiên Yên', 
											'235' => 'Huyện Ba Chẽ', 
											'236' => 'Huyện Vân Đồn', 
											'237' => 'Huyện Hoành Bồ', 
											'238' => 'Huyện Đông Triều', 
											'239' => 'Huyện Cô Tô', 
											'240' => 'Huyện Yên Hưng', 
							), 
							'301' => array('241' => 'Không xác định', 
											'242' => 'Thị xã Điện Biên Phủ', 
											'243' => 'Thị xã Lai Châu', 
											'244' => 'Huyện Mường Tè', 
											'245' => 'Huyện Phong Thổ', 
											'246' => 'Huyện Sìn Hồ', 
											'247' => 'Huyện Mường Lay', 
											'248' => 'Huyện Tủa Chùa', 
											'249' => 'Huyện Tuần Giáo', 
											'250' => 'Huyện Điện Biên', 
											'251' => 'Huyện Điện Biên Đông', 
							), 
							'303' => array('252' => 'Không xác định', 
											'253' => 'Thị xã Sơn La', 
											'254' => 'Huyện Quỳnh Nhai', 
											'255' => 'Huyện Mường La', 
											'256' => 'Huyện Thuận Châu', 
											'257' => 'Huyện Bắc Yên', 
											'258' => 'Huyện Phù Yên', 
											'259' => 'Huyện Mai Sơn', 
											'260' => 'Huyện Sông Mã', 
											'261' => 'Huyện Yên Châu', 
											'262' => 'Huyện Mộc Châu'
							), 
							'305' => array('263' => 'Không xác định', 
											'264' => 'Thị xã Hòa Bình', 
											'265' => 'Huyện Đà Bắc', 
											'266' => 'Huyện Mai Châu', 
											'267' => 'Huyện Kỳ Sơn', 
											'268' => 'Huyện Lương Sơn', 
											'269' => 'Huyện Kim Bôi', 
											'270' => 'Huyện Tân Lạc', 
											'271' => 'Huyện Lạc Sơn', 
											'272' => 'Huyện Lạc Thủy', 
											'273' => 'Huyện Yên Thủy' 
							), 
							'401' => array('274' => 'Không xác định', 
											'275' => 'Thành phố Thanh Hóa', 
											'276' => 'Thị xã Bỉm Sơn', 
											'277' => 'Thị xã Sầm Sơn', 
											'278' => 'Huyện Mường Lát', 
											'279' => 'Huyện Quan Hóa', 
											'280' => 'Huyện Quan Sơn', 
											'281' => 'Huyện Bá Thước', 
											'282' => 'Huyện Cẩm Thủy', 
											'283' => 'Huyện Lang Chánh', 
											'284' => 'Huyện Thạch Thành', 
											'285' => 'Huyện Ngọc Lạc', 
											'286' => 'Huyện Thường Xuân', 
											'287' => 'Huyện Như Xuân', 
											'288' => 'Huyện Như Thanh', 
											'289' => 'Huyện Vĩnh Lộc', 
											'290' => 'Huyện Hà Trung', 
											'291' => 'Huyện Nga Sơn', 
											'292' => 'Huyện Yên Định', 
											'293' => 'Huyện Thọ Xuân', 
											'294' => 'Huyện Hậu Lộc', 
											'295' => 'Huyện Thiệu Hoá', 
											'296' => 'Huyện Hoằng Hóa', 
											'297' => 'Huyện Đông Sơn', 
											'298' => 'Huyện Triệu Sơn', 
											'299' => 'Huyện Quảng Xương', 
											'300' => 'Huyện Nông Cống', 
											'301' => 'Huyện Tĩnh Gia' 
							), 
							'403' => array('302' => 'Không xác định', 
											'303' => 'Thành phố Vinh', 
											'304' => 'Thị xã Cửa Lò', 
											'305' => 'Huyện Quế Phong', 
											'306' => 'Huyện Quỳ Châu', 
											'307' => 'Huyện Kỳ Sơn', 
											'308' => 'Huyện Quỳ Hợp', 
											'309' => 'Huyện Nghĩa Đàn', 
											'310' => 'Huyện Tương Dương', 
											'311' => 'Huyện Quỳnh Lưu', 
											'312' => 'Huyện Tân Kỳ', 
											'313' => 'Huyện Con Cuông', 
											'314' => 'Huyện Yên Thành', 
											'315' => 'Huyện Diễn Châu', 
											'316' => 'Huyện Anh Sơn', 
											'317' => 'Huyện Đô Lương', 
											'318' => 'Huyện Thanh Chương', 
											'319' => 'Huyện Nghi Lộc', 
											'320' => 'Huyện Nam Đàn', 
											'321' => 'Huyện Hưng Nguyên'
							), 
							'405' => array('322' => 'Không xác định', 
											'323' => 'Thị xã Hà Tĩnh', 
											'324' => 'Thị xã Hồng Lĩnh', 
											'325' => 'Huyện Nghi Xuân', 
											'326' => 'Huyện Đức Thọ', 
											'327' => 'Huyện Hương Sơn', 
											'328' => 'Huyện Can Lộc', 
											'329' => 'Huyện Thạch Hà', 
											'330' => 'Huyện Cẩm Xuyên', 
											'331' => 'Huyện Hương Khê', 
											'332' => 'Huyện Kỳ Anh' 
							), 
							'407' => array('333' => 'Không xác định', 
											'334' => 'Thị xã Đồng Hới', 
											'335' => 'Huyện Tuyên Hóa', 
											'336' => 'Huyện Minh Hóa', 
											'337' => 'Huyện Quảng Trạch', 
											'338' => 'Huyện Bố Trạch', 
											'339' => 'Huyện Quảng Ninh', 
											'340' => 'Huyện Lệ Thủy' 
							), 
							'409' => array('341' => 'Không xác định', 
											'342' => 'Thị xã Đông Hà', 
											'343' => 'Thị xã Quảng Trị', 
											'344' => 'Huyện Vĩnh Linh', 
											'345' => 'Huyện Gio Linh', 
											'346' => 'Huyện Cam Lộ', 
											'347' => 'Huyện Triệu Phong', 
											'348' => 'Huyện Hải Lăng', 
											'349' => 'Huyện Hướng Hóa', 
											'350' => 'Huyện Đa Krông'
							), 
							'411' => array('351' => 'Không xác định', 
											'352' => 'Thành phố Huế', 
											'353' => 'Huyện Phong Điền', 
											'354' => 'Huyện Quảng Điền', 
											'355' => 'Huyện Hương Trà', 
											'356' => 'Huyện Phú Vang', 
											'357' => 'Huyện Hương Thủy', 
											'358' => 'Huyện Phú Lộc', 
											'359' => 'Huyện A Lưới', 
											'360' => 'Huyện Nam Đông' 
							), 
							'501' => array('361' => 'Không xác định', 
											'362' => 'Quận Hải Châu', 
											'363' => 'Quận Thanh Khê', 
											'364' => 'Quận Sơn Trà', 
											'365' => 'Quận Ngũ Hành Sơn', 
											'366' => 'Quận Liên Chiểu', 
											'367' => 'Huyện Hoà Vang', 
											'368' => 'Huyện Đảo Hoàng Sa'
							), 
							'503' => array('369' => 'Không xác định', 
											'370' => 'Thị xã Tam Kỳ', 
											'371' => 'Thị xã Hội An', 
											'372' => 'Huyện Hiên', 
											'373' => 'Huyện Đại Lộc', 
											'374' => 'Huyện Điện Bàn', 
											'375' => 'Huyện Duy Xuyên', 
											'376' => 'Huyện Giằng', 
											'377' => 'Huyện Thăng Bình', 
											'378' => 'Huyện Quế Sơn', 
											'379' => 'Huyện Hiệp Đức', 
											'380' => 'Huyện Tiên Phước', 
											'381' => 'Huyện Phước Sơn', 
											'382' => 'Huyện Núi Thành', 
											'383' => 'Huyện Trà My', 
							), 
							'505' => array('384' => 'Không xác định', 
											'385' => 'Thị xã Quảng Ngãi', 
											'386' => 'Huyện Lý Sơn', 
											'387' => 'Huyện Bình Sơn', 
											'388' => 'Huyện Trà Bồng', 
											'389' => 'Huyện Sơn Tịnh', 
											'390' => 'Huyện Sơn Tây', 
											'391' => 'Huyện Sơn Hà', 
											'392' => 'Huyện Tư Nghĩa', 
											'393' => 'Huyện Nghĩa Hành', 
											'394' => 'Huyện Minh Long', 
											'395' => 'Huyện Mộ Đức', 
											'396' => 'Huyện Đức Phổ', 
											'397' => 'Huyện Ba Tơ', 
							), 
							'507' => array('398' => 'Không xác định', 
											'399' => 'Thành phố Qui Nhơn', 
											'400' => 'Huyện An Lão', 
											'401' => 'Huyện Hoài Nhơn', 
											'402' => 'Huyện Hoài Ân', 
											'403' => 'Huyện Phù Mỹ', 
											'404' => 'Huyện Vĩnh Thạnh', 
											'405' => 'Huyện Phù Cát', 
											'406' => 'Huyện Tây Sơn', 
											'407' => 'Huyện An Nhơn', 
											'408' => 'Huyện Tuy Phước', 
											'409' => 'Huyện Vân Canh', 
							), 
							'509' => array('410' => 'Không xác định', 
											'411' => 'Thị xã Tuy Hòa', 
											'412' => 'Huyện Đồng Xuân', 
											'413' => 'Huyện Sông Cầu', 
											'414' => 'Huyện Tuy An', 
											'415' => 'Huyện Sơn Hòa', 
											'416' => 'Huyện Tuy Hòa', 
											'417' => 'Huyện Sông Hinh', 
							), 
							'511' => array('418' => 'Không xác định', 
											'419' => 'Thành phố Nha Trang', 
											'420' => 'Huyện Vạn Ninh', 
											'421' => 'Huyện Ninh Hòa', 
											'422' => 'Huyện Diên Khánh', 
											'423' => 'Huyện Cam Ranh', 
											'424' => 'Huyện Khánh Vĩnh', 
											'425' => 'Huyện Khánh Sơn', 
											'426' => 'Huyện Trường Sa', 
							), 
							'601' => array('427' => 'Không xác định', 
											'428' => 'Thị xã Kon Tum', 
											'429' => 'Huyện Đắk Glei', 
											'430' => 'Huyện Ngọc Hồi', 
											'431' => 'Huyện Đắk Tô', 
											'432' => 'Huyện Kon Plông', 
											'433' => 'Huyện Đak Hà', 
											'434' => 'Huyện Sa Thầy', 
							), 
							'603' => array('435' => 'Không xác định', 
											'436' => 'Thị xã Pleiku', 
											'437' => 'Huyện KBang', 
											'438' => 'Huyện Mang Yang', 
											'439' => 'Huyện Chư Păh', 
											'440' => 'Huyện Ia Grai', 
											'441' => 'Huyện An Khê', 
											'442' => 'Huyện Kông Chro', 
											'443' => 'Huyện Đức Cơ', 
											'444' => 'Huyện Chư Prông', 
											'445' => 'Huyện Chư Sê', 
											'446' => 'Huyện Ayun Pa', 
											'447' => 'Huyện Krông Pa', 
							), 
							'605' => array('448' => 'Không xác định', 
											'449' => 'Thành phố Buôn Ma Thuột', 
											'450' => 'Huyện Ea H', 
											'451' => 'Huyện Ea Súp', 
											'452' => 'Huyện Krông Năng', 
											'453' => 'Huyện Krông Búk', 
											'454' => 'Huyện Buôn Đôn', 
											'455' => 'Huyện Cư M', 
											'456' => 'Huyện Ea Kar', 
											'457' => 'Huyện M', 
											'458' => 'Huyện Krông Pắc', 
											'459' => 'Huyện Cư Jút', 
											'460' => 'Huyện Krông A Na', 
											'461' => 'Huyện Krông Bông', 
											'462' => 'Huyện Đắk Mil', 
											'463' => 'Huyện Krông Nô', 
											'464' => 'Huyện Lắk', 
											'465' => 'Huyện Đắk R', 
											'466' => 'Huyện Đắk Nông', 
							), 
							'701' => array('467' => 'Không xác định', 
											'468' => 'Quận 1', 
											'469' => 'Quận 2', 
											'470' => 'Quận 3', 
											'471' => 'Quận 4', 
											'472' => 'Quận 5', 
											'473' => 'Quận 6', 
											'474' => 'Quận 7', 
											'475' => 'Quận 8', 
											'476' => 'Quận 9', 
											'477' => 'Quận 10', 
											'478' => 'Quận 11', 
											'479' => 'Quận 12', 
											'480' => 'Quận Gò Vấp', 
											'481' => 'Quận Tân Bình', 
											'482' => 'Quận Bình Thạnh', 
											'483' => 'Quận Phú Nhuận', 
											'484' => 'Quận Thủ Đức', 
											'485' => 'Huyện Củ Chi', 
											'486' => 'Huyện Hóc Môn', 
											'487' => 'Huyện Bình Chánh', 
											'488' => 'Huyện Nhà Bè', 
											'489' => 'Huyện Cần Giờ', 
							), 
							'703' => array('490' => 'Không xác định', 
											'491' => 'Thành phố Đà Lạt', 
											'492' => 'Thị xã Bảo Lộc', 
											'493' => 'Huyện Lạc Dương', 
											'494' => 'Huyện Đơn Dương', 
											'495' => 'Huyện Đức Trọng', 
											'496' => 'Huyện Lâm Hà', 
											'497' => 'Huyện Bảo Lâm', 
											'498' => 'Huyện Di Linh', 
											'499' => 'Huyện Đạ Huoai', 
											'500' => 'Huyện Đạ Tẻh', 
											'501' => 'Huyện Cát Tiên', 
							), 
							'705' => array('502' => 'Không xác định', 
											'503' => 'Thị xã Phan Rang-Tháp Chàm', 
											'504' => 'Huyện Ninh Sơn', 
											'505' => 'Huyện Ninh Hải', 
											'506' => 'Huyện Ninh Phước', 
							), 
							'707' => array('507' => 'Không xác định', 
											'508' => 'Huyện Đồng Phú', 
											'509' => 'Huyện Phước Long', 
											'510' => 'Huyện Lộc Ninh', 
											'511' => 'Huyện Bù Đăng', 
											'512' => 'Huyện Bình Long', 
							), 
							'709' => array('513' => 'Không xác định', 
											'514' => 'Thị xã Tây Ninh', 
											'515' => 'Huyện Tân Biên', 
											'516' => 'Huyện Tân Châu', 
											'517' => 'Huyện Dương Minh Châu', 
											'518' => 'Huyện Châu Thành', 
											'519' => 'Huyện Hòa Thành', 
											'520' => 'Huyện Bến Cầu', 
											'521' => 'Huyện Gò Dầu', 
											'522' => 'Huyện Trảng Bàng', 
							), 
							'711' => array('523' => 'Không xác định', 
											'524' => 'Thị xã Thủ Dầu Một', 
											'525' => 'Huyện Bến Cát', 
											'526' => 'Huyện Tân Uyên', 
											'527' => 'Huyện Thuận An', 
							), 
							'713' => array('528' => 'Không xác định', 
											'529' => 'Thành phố Biên Hòa', 
											'530' => 'Huyện Tân Phú', 
											'531' => 'Huyện Định Quán', 
											'532' => 'Huyện Vĩnh Cừu', 
											'533' => 'Huyện Thống Nhất', 
											'534' => 'Huyện Long Khánh', 
											'535' => 'Huyện Xuân Lộc', 
											'536' => 'Huyện Long Thành', 
											'537' => 'Huyện Nhơn Trạch', 
							), 
							'715' => array('538' => 'Không xác định', 
											'539' => 'Thị xã Phan Thiết', 
											'540' => 'Huyện Tuy Phong', 
											'541' => 'Huyện Bắc Bình', 
											'542' => 'Huyện Hàm Thuận Bắc', 
											'543' => 'Huyện Hàm Thuận Nam', 
											'544' => 'Huyện Tánh Linh', 
											'545' => 'Huyện Hàm Tân', 
											'546' => 'Huyện Đức Linh', 
											'547' => 'Huyện Phú Quí', 
							), 
							'717' => array('548' => 'Không xác định', 
											'549' => 'Thành phố Vũng Tàu', 
											'550' => 'Thị xã Bà Rịa', 
											'551' => 'Huyện Châu Đức', 
											'552' => 'Huyện Xuyên Mộc', 
											'553' => 'Huyện Tân Thành', 
											'554' => 'H.LĐất', 
											'555' => 'Huyện Côn Đảo', 
							), 
							'801' => array('556' => 'Không xác định', 
											'557' => 'Thị xã Tân An', 
											'558' => 'Huyện Tân Hưng', 
											'559' => 'Huyện Vĩnh Hưng', 
											'560' => 'Huyện Mộc Hóa', 
											'561' => 'Huyện Tân Thạnh', 
											'562' => 'Huyện Thạnh Hóa', 
											'563' => 'Huyện Đức Huệ', 
											'564' => 'Huyện Đức Hòa', 
											'565' => 'Huyện Bến Lức', 
											'566' => 'Huyện Thủ Thừa', 
											'567' => 'Huyện Châu Thành', 
											'568' => 'Huyện Tân Trụ', 
											'569' => 'Huyện Cần Đước', 
											'570' => 'Huyện Cần Giuộc', 
							), 
							'803' => array('571' => 'Không xác định', 
											'572' => 'Thị xã Cao Lãnh', 
											'573' => 'Thị xã Sa Đéc', 
											'574' => 'Huyện Tân Hồng', 
											'575' => 'Huyện Hồng Ngự', 
											'576' => 'Huyện Tam Nông', 
											'577' => 'Huyện Thanh Bình', 
											'578' => 'Huyện Tháp Mười', 
											'579' => 'Huyện Cao Lãnh', 
											'580' => 'Huyện Lấp Vò', 
											'581' => 'Huyện Lai Vung', 
											'582' => 'Huyện Châu Thành', 
							), 
							'805' => array('583' => 'Không xác định', 
											'584' => 'Thị xã Long Xuyên', 
											'585' => 'Thị xã Châu Đốc', 
											'586' => 'Huyện An Phú', 
											'587' => 'Huyện Tân Châu', 
											'588' => 'Huyện Phú Tân', 
											'589' => 'Huyện Châu Phú', 
											'590' => 'Huyện Tịnh Biên', 
											'591' => 'Huyện Tri Tôn', 
											'592' => 'Huyện Chợ Mới', 
											'593' => 'Huyện Châu Thành', 
											'594' => 'Huyện Thoại Sơn', 
							), 
							'807' => array('595' => 'Không xác định', 
											'596' => 'Thành phố Mỹ Tho', 
											'597' => 'Thị xã Gò Công', 
											'598' => 'Huyện Tân Phước', 
											'599' => 'Huyện Châu Thành', 
											'600' => 'Huyện Cai Lậy', 
											'601' => 'Huyện Chợ Gạo', 
											'602' => 'Huyện Cái Bè', 
											'603' => 'Huyện Gò Công Tây', 
											'604' => 'Huyện Gò Công Đông', 
							), 
							'809' => array('605' => 'Không xác định', 
							'606' => 'Thị xã Vĩnh Long', 
							'607' => 'Huyện Long Hồ', 
							'608' => 'Huyện Mang Thít', 
							'609' => 'Huyện Bình Minh', 
							'610' => 'Huyện Tam Bình', 
							'611' => 'Huyện Trà Ôn', 
							'612' => 'Huyện Vũng Liêm', 
							), 
							'811' => array('613' => 'Không xác định', 
							'614' => 'Thị xã Bến Tre', 
							'615' => 'Huyện Châu Thành', 
							'616' => 'Huyện Chợ Lách', 
							'617' => 'Huyện Mỏ Cày', 
							'618' => 'Huyện Giồng Trôm', 
							'619' => 'Huyện Bình Đại', 
							'620' => 'Huyện Ba Tri', 
							'621' => 'Huyện Thạnh Phú', 
							), 
							'813' => array('622' => 'Không xác định', 
							'623' => 'Thị xã Rạch Giá', 
							'624' => 'Huyện Hà Tiên', 
							'625' => 'Huyện Hòn Đất', 
							'626' => 'Huyện Tân Hiệp', 
							'627' => 'Huyện Châu Thành', 
							'628' => 'Huyện Giồng Giềng', 
							'629' => 'Huyện Gò Quao', 
							'630' => 'Huyện An Biên', 
							'631' => 'Huyện An Minh', 
							'632' => 'Huyện Vĩnh Thuận', 
							'633' => 'Huyện Phú Quốc', 
							'634' => 'Huyện Kiên Hải', 
							'635' => 'Thị xã Hà Tiên', 
							), 
							'815' => array('636' => 'Không xác định', 
							'637' => 'Thành phố Cần Thơ', 
							'638' => 'Thị xã Vị Thanh', 
							'639' => 'Huyện Thốt Nốt', 
							'640' => 'Huyện Ô Môn', 
							'641' => 'Huyện Châu Thành', 
							'642' => 'Huyện Phụng Hiệp', 
							'643' => 'Huyện Vị Thuỷ', 
							'644' => 'Huyện Long Mỹ', 
							), 
							'817' => array('645' => 'Không xác định', 
							'646' => 'Thị xã Trà Vinh', 
							'647' => 'Huyện Càng Long', 
							'648' => 'Huyện Châu Thành', 
							'649' => 'Huyện Cầu Kè', 
							'650' => 'Huyện Tiểu Cần', 
							'651' => 'Huyện Cầu Ngang', 
							'652' => 'Huyện Trà Cú', 
							'653' => 'Huyện Duyên Hải', 
							), 
							'819' => array('654' => 'Không xác định', 
							'655' => 'Thị xã Sóc Trăng', 
							'656' => 'Huyện Kế Sách', 
							'657' => 'Huyện Long Phú', 
							'658' => 'Huyện Mỹ Tú', 
							'659' => 'Huyện Mỹ Xuyên', 
							'660' => 'Huyện Thạnh Trị', 
							'661' => 'Huyện Vĩnh Châu', 
							), 
							'821' => array('662' => 'Không xác định', 
							'663' => 'Thị xã Bạc Liêu', 
							'664' => 'Huyện Hồng Dân', 
							'665' => 'Huyện Vĩnh Lợi', 
							'666' => 'Huyện Giá Rai', 
							), 
							'823' => array('667' => 'Không xác định', 
							'668' => 'Thị xã Cà Mau', 
							'669' => 'Huyện Thới Bình', 
							'670' => 'Huyện U Minh', 
							'671' => 'Huyện Trần Văn Thời', 
							'672' => 'Huyện Cái Nước', 
							'673' => 'Huyện Đầm Dơi', 
							'674' => 'Huyện Ngọc Hiển', 
							), 
		);
		
		return $districts;
	}
}